version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: carewell_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
      
  backend:
    build: ./backend
    volumes:
      - backend_source:/usr/src/app
      - backend_node_modules:/usr/src/app/node_modules
      - uploads:/usr/src/app/uploads
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: mypassword
      DB_NAME: carewell_db

  frontend:
    build: ./frontend
    volumes:
      - frontend_source:/usr/src/app
      - frontend_node_modules:/usr/src/app/node_modules
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: ["npm", "start"]

volumes:
  mysql_data:
    name: carewell_ehr_mysql_data
  backend_node_modules:
    name: carewell_ehr_backend_node_modules
  frontend_node_modules:
    name: carewell_ehr_frontend_node_modules
  uploads:
    name: carewell_ehr_uploads
  backend_source:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./backend
  frontend_source:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./frontend
